version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: campanhas360
      POSTGRES_USER: bolt360ti
      POSTGRES_PASSWORD: Bolt360@@!
    ports:
      - '3101:5432'  # Porta do PostgreSQL exposta em 3101
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - saas-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bolt360ti -d campanhas360"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: bolt360@admin.com
      PGADMIN_DEFAULT_PASSWORD: bolt360ti@!@
    ports:
      - '3102:80'  # Porta do PgAdmin exposta em 3102
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - saas-network

  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "3103:8080"  # Porta da Evolution API exposta em 3103
    environment:
      PORT: 2345
      POSTGRES_PORT: 5432
      POSTGRES_DB: evolution
      POSTGRES_USER: bolt360ti
      POSTGRES_PASSWORD: Bolt360@@!
      JWT_SECRET: kasdjasidaau1n213mmaaasdncksk
      PRODUCTION: true
      MINIO_ROOT_USER: bolt360ti
      MINIO_ROOT_PASSWORD: Gmais2023@!!@
      MINIO_BUCKET: evolution-assets
      MINIO_ENDPOINT: minio
      MINIO_USE_SSL: false
      MINIO_PORT: 9000
      AUTHENTICATION_API_KEY: kasdjasidaau1n213mmaaasdncksk
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://bolt360ti:Bolt360@@!@postgres:5432/evolution
      S3_ENABLED: true
      S3_ACCESS_KEY: bolt360ti
      S3_SECRET_KEY: Gmais2023@!!@
      S3_BUCKET: evolution-assets
      S3_ENDPOINT: minio
      S3_USE_SSL: false
      CACHE_REDIS_ENABLED: true
      CACHE_REDIS_URI: redis://redis:6379/6
      CACHE_REDIS_PREFIX_KEY: evolution
      CACHE_REDIS_SAVE_INSTANCES: false
      CACHE_LOCAL_ENABLED: false
      URL_EVOLUTION_API: http://localhost:8080
      EVOLUTION_API_KEY: sua_chave_api_aqui
      BASE_URL: http://host.docker.internal:2345
    depends_on:
      - postgres
      - minio
      - redis
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - saas-network

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: bolt360ti
      MINIO_ROOT_PASSWORD: Gmais2023@!!@
    ports:
      - "3104:9000"  # Porta do MinIO exposta em 3104
      - "3105:9001"  # Console do MinIO exposto em 3105
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - saas-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "3106:6379"  # Porta do Redis exposta em 3106
    volumes:
      - redis-data:/data
    networks:
      - saas-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: saas_backend
    restart: always
    ports:
      - "3107:2345"  # Porta do Backend exposta em 3107
    environment:
      NODE_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: campanhas360
      POSTGRES_USER: bolt360ti
      POSTGRES_PASSWORD: Bolt360@@!
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - saas-network

volumes:
  postgres-data:
  pgadmin-data:
  evolution_instances:
  minio-data:
  redis-data:

networks:
  saas-network:
    name: saas-network
    driver: bridge
